### ISSUE TITLE
[CI] Cleanup errant workflows

### ISSUE THREAD

**Issue by leecalcote** [layer5io/mesheryctl-smi-conformance-action#3]
@leecalcote should i delete some of these workflows ? my brain wouldn't let me rest if these red checkmarks are here

_Originally posted by @s1ntaxe770r in https://github.com/layer5io/mesheryctl-smi-conformance-action/issues/2#issuecomment-831231311_

**Comment by s1ntaxe770r** [comment]
have cleaned up most of them, should i delete release-drafter.yml as well? i don't think we'd be releasing anything for a while

**Comment by leecalcote** [comment]
No, please leave releasedrafter.yml and stale.yml, and config.yml.
